### Get the list of commerces
GET http://localhost:3000/api/commerces/view-all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU0ZTMxYWUwZjRhYWIyYjU0OGFmYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMDEyNjUzNywiZXhwIjoxNzMwMTMzNzM3fQ.zIRzpGFBeflxE-5XxwPrXKOU7IEfTJWENaokGlGllQg

### Get a commerce by its CIF
GET http://localhost:3000/api/commerces/A12345678

### Save a new commerce
POST http://localhost:3000/api/commerces
Content-Type: application/json

{
  "name": "New Commerce",
  "cif": "A12345678",
  "address": "123 Fake Street",
  "email": "newcommerce@example.com",
  "phone": "123-456-7890",
  "pageId": 1
}

### Update a commerce by its CIF
PUT http://localhost:3000/api/commerces/A12345678
Content-Type: application/json

{
  "name": "Updated Commerce",
  "address": "742 Evergreen Terrace",
  "email": "updatedcommerce@example.com",
  "phone": "098-765-4321",
  "pageId": 2
}

### Delete a commerce by its CIF (logical deletion)
DELETE http://localhost:3000/api/commerces/A12345678?borrado=logico

### Delete a commerce by its CIF (physical deletion)
DELETE http://localhost:3000/api/commerces/A12345678?borrado=fisico