### Get the list of commerces
GET http://localhost:3000/api/commerces/view-all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMjAyODczMCwiZXhwIjoxNzMyMDM1OTMwfQ.KTmaW4DqbIcpagi1qbx043_PHG7dPT5x-9XUZHUjc1s

###
GET http://localhost:3000/api/commerces/view/A87654324
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMjUzMTU1MiwiZXhwIjoxNzMyNTM4NzUyfQ.2b5BCv1xb9_7lPlYVCVCzOnsQ5Y4yS8Dewfmp_kU-EE

### Get a commerce by its CIF
POST http://localhost:3000/api/commerces/create/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMjUzMjUyMywiZXhwIjoxNzMyNTM5NzIzfQ.XgMKU0DsdIJZufd5rKxc7tZzheZoCTSaMgitlFnDRZw
Content-Type: application/json

{
  "name": "New Commerce",
  "cif": "A87654324",
  "address": "123 Fake Street",
  "email": "newcommerce@example.com",
  "phone": "123-456-7890",
  "pageId": 1
}

### Update a commerce by its CIF
PUT http://localhost:3000/api/commerces/update/A87654324
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMDIxMDc4MywiZXhwIjoxNzMwMjE3OTgzfQ.N8Wa20zaPo3iVjBVYcnu7hWJRyA1Y9brbmXKefPBZ5I
Content-Type: application/json

{
  "name": "Updated Commerce",
  "address": "742 Evergreen Terrace",
  "email": "updatedcommerce@example.com",
  "phone": "098-765-4321",
  "pageId": 2
}

### Delete a commerce by its CIF (logical deletion)
DELETE http://localhost:3000/api/commerces/delete/A87654324
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMDE4ODY5MCwiZXhwIjoxNzMwMTk1ODkwfQ.qMYnnKSVbRqRbB3kLOMtj72hMIf-LcKPtYTIvGIAWQ0

###
GET http://localhost:3000/api/users/interested
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBODc2NTQzMjQiLCJpYXQiOjE3MzAyNDE3NTUsImV4cCI6MTczMDI0ODk1NX0.5MAbShNhxgl93Ec0_NEjfRySjFRFVpNY4MYVMkzzoyo

### Create 3 new commerces
POST http://localhost:3000/api/commerces/create/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMTg2NzMwNSwiZXhwIjoxNzMxODc0NTA1fQ.mfNyf3Q6-I38JXmoEU_gY2iVelUbg10r2YBTkIM_eLE
Content-Type: application/json

{
  "name": "Commerce",
  "cif": "A12345678",
  "address": "123 Commerce Street",
  "email": "commerce1@example.com",
  "phone": "111-11-1111",
  "pageId": 4
}
###
POST http://localhost:3000/api/commerces/create/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMTg2NzMwNSwiZXhwIjoxNzMxODc0NTA1fQ.mfNyf3Q6-I38JXmoEU_gY2iVelUbg10r2YBTkIM_eLE
Content-Type: application/json

{
  "name": "Commerce 2",
  "cif": "A23456789",
  "address": "234 Commerce Street",
  "email": "commerce2@example.com",
  "phone": "222-222-2222",
  "pageId": 2
}
###
POST http://localhost:3000/api/commerces/create/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBMzQ1Njc4OTAiLCJpYXQiOjE3MzE4Njc5MDEsImV4cCI6MTczMTg3NTEwMX0.j0YnfAO9cyDJKdItsVJuobpWLUQMYWkxi-3rDebPK_w

{
  "name": "Commerce 3",
  "cif": "A34567890",
  "address": "345 Commerce Street",
  "email": "commerce3@example.com",
  "phone": "333-333-3333",
  "pageId": 3
}


### Update a webCommerce by its CIF

PUT http://localhost:3000/api/webCommerce/update/A87654324
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBODc2NTQzMjQiLCJpYXQiOjE3MzAyMzM5MTIsImV4cCI6MTczMDI0MTExMn0.j8tlUbUYuaaCSKlNyvZlYNAyRS4xDK6nw_PyaLa0xX0
Content-Type: application/json

{
    "city": "Madridd",
    "activity": "Retaild",
    "title": "My Web Commerce",
    "summary": "This is a summary of my web commerce.",
    "text": ["Introduction", "Details", "Conclusionn"],
    "isArchived": false
}