### Get webCommerce by its CIF

GET http://localhost:3000/api/webCommerce/view/A87654324
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjA5MGMwMjZiMjAwM2Q0YzZjMzI2ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMjUyOTc2MywiZXhwIjoxNzMyNTM2OTYzfQ.q10mheVXGETcgcdKP6mzU6f3cGeJ-fYZzzi-FpmET54

### Save a new webCommerce with model data
POST http://localhost:3000/api/webCommerce/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBODc2NTQzMjQiLCJpYXQiOjE3MzI1MzI1MzksImV4cCI6MTczMjUzOTczOX0.viQSgLV2i-9fb4sEw1DeV1Q94r1dxxZxFAJhG12TR98
Content-Type: application/json

{
    "city": "Madrid",
    "activity": "Retail",
    "title": "My Web Commerce",
    "summary": "This is a summary of my web commerce.",
    "text": ["Introduction", "Details", "Conclusion"],
    "commerceCIF": "A87654324"
}

### Update a webCommerce by its CIF

PUT http://localhost:3000/api/webCommerce/update/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBODc2NTQzMjQiLCJpYXQiOjE3MzI1MjA5NjgsImV4cCI6MTczMjUyODE2OH0.RCg_zT0RKXcncbRLLtNQ08gJklbxD-BUnWpsc2fdWMk
Content-Type: application/json

{
    "city": "Madridd",
    "activity": "Retaild",
    "title": "My Web Commerce",
    "summary": "This is a summary of my web commerce.",
    "text": ["Introduction", "Details", "Conclusionn"],
    "isArchived": false
}


### Archive a webCommerce by its CIF

DELETE http://localhost:3000/api/webCommerce/A87654321?action=archive
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBODc2NTQzMjQiLCJpYXQiOjE3MzAyMzM5MTIsImV4cCI6MTczMDI0MTExMn0.j8tlUbUYuaaCSKlNyvZlYNAyRS4xDK6nw_PyaLa0xX0


### Delete a webCommerce by its CIF

DELETE http://localhost:3000/api/webCommerce/A87654321?action=delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjE2NmEyNjZmNGYxZjYyNTdmNGI3ZCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxNjk4MjQxLCJleHAiOjE3MzE3MDU0NDF9.EzBY9UdPo6y-aZTGel7WEHsBIILaos3l7mssa_A9aPs


### Upload an image to a webCommerce
PATCH http://localhost:3000/api/webCommerce/upload/A87654321/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWYiOiJBODc2NTQzMjQiLCJpYXQiOjE3MzAyMzM5MTIsImV4cCI6MTczMDI0MTExMn0.j8tlUbUYuaaCSKlNyvZlYNAyRS4xDK6nw_PyaLa0xX0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

< /Users/nicolaspertierra/Developer/2CEB/2CEB/Fullstack_web_programming/server/mvc_commerce/images/image_1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

